/**
 * Generate mailto: links with pre-filled complaint emails.
 *
 * Creates a ready-to-click link that opens the user's default email
 * client with subject, body, and optional CC pre-populated from the
 * civic issue data.
 */

import type { CivicIssue } from "../types/issue";

export interface MailtoOptions {
  /** Recipient email address. Falls back to a generic placeholder. */
  to?: string;
  /** Optional CC addresses. */
  cc?: string[];
}

/**
 * Build a `mailto:` URL from a civic issue and an optional authority email.
 */
export function generateMailtoLink(
  issue: CivicIssue,
  options: MailtoOptions = {},
): string {
  const to = options.to || "";
  const subject = `[Civic Report] ${issue.title}`;

  const body = [
    `Subject: ${issue.title}`,
    "",
    `Category: ${issue.category}`,
    `Severity: ${issue.severity}`,
    `Location: ${issue.location.text}`,
    `Status: ${issue.status}`,
    `Date: ${new Date(issue.createdAt).toLocaleDateString("en-IN", { dateStyle: "long" })}`,
    "",
    "--- Complaint ---",
    "",
    issue.complaintMessage,
    "",
    "--- Summary ---",
    "",
    issue.summary,
    "",
    "--- Missing Information ---",
    "",
    ...(issue.missingInfo.length > 0
      ? issue.missingInfo.map((item) => `• ${item}`)
      : ["No additional information needed."]),
    "",
    "--- Volunteer Action ---",
    "",
    issue.volunteerAction,
    "",
    "---",
    "This report was generated by ParaPulse — AI-powered civic issue reporting.",
  ].join("\n");

  const params = new URLSearchParams();
  params.set("subject", subject);
  params.set("body", body);
  if (options.cc && options.cc.length > 0) {
    params.set("cc", options.cc.join(","));
  }

  return `mailto:${encodeURIComponent(to)}?${params.toString()}`;
}

/**
 * Build a shareable plain-text version of the complaint for
 * copy-paste into portals or messaging apps.
 */
export function generateComplaintText(issue: CivicIssue): string {
  return [
    `📋 ${issue.title}`,
    "",
    `📍 Location: ${issue.location.text}`,
    `⚠️ Severity: ${issue.severity}`,
    `🏷️ Category: ${issue.category}`,
    "",
    issue.complaintMessage,
    "",
    "— Generated by ParaPulse",
  ].join("\n");
}
